apiVersion: v1
entries:
  spark-test:
  - apiVersion: v1
    appVersion: 2.4.2
    created: 2019-05-22T18:13:05.805766-07:00
    description: A Helm chart for Spark cluster with Livy atop Kubernetes
    digest: 36510db25bc0d48bcedde2616c4e1af618898537946b5517edb16a817e5f6b57
    keywords:
    - livy
    - spark
    - history-server
    name: spark-test
    urls:
    - https://arunmahadevan.github.io/charts/spark-test-0.1.0.tgz
    version: 0.1.0
  testapp:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-05-22T18:13:05.809354-07:00
    description: A Helm chart for test app
    digest: 7d12976deb766bef5701500c66ca6ae355e453f32c5d00155e2994d54c3879f7
    name: testapp
    urls:
    - https://arunmahadevan.github.io/charts/testapp-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-05-22T18:13:05.808835-07:00
    description: A Helm chart for test app
    digest: 75376b60e0697cea7629c98a84c8f60547e9fe7dc1df8a8039c83c31d65918ae
    name: testapp
    urls:
    - https://arunmahadevan.github.io/charts/testapp-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-05-22T18:13:05.807021-07:00
    description: A Helm chart for test app
    digest: a4f3db4a517981766a0d944e4e66f1b4677474ad1b0f7c523c3c7256b0dfb505
    name: testapp
    urls:
    - https://arunmahadevan.github.io/charts/testapp-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-05-22T18:13:05.806454-07:00
    description: A Helm chart for test app
    digest: 815c263d11e3ed6329a3e6a8df5907adca69c0c00838f60e9422d00145cb44db
    name: testapp
    urls:
    - https://arunmahadevan.github.io/charts/testapp-0.1.0.tgz
    version: 0.1.0
generated: 2019-05-22T18:13:05.801656-07:00
